name: Lint BE

on:
  push:
    paths:
      - "**/*.py"

jobs:
  flake8:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
          architecture: x64
      - name: Checkout Phoqer
        uses: actions/checkout@v2
      - name: Install flake8 and plugins
        run: pip install flake8==3.8.4 flake8-pytest-style==1.3.0 flake8-formatter-abspath==1.0.1
      - name: Run flake8
        run: flake8
        working-directory: ./FastAPI
